# Dockerfile for the client

FROM obraun/vss-protoactor-jenkins as builder
COPY . /app
WORKDIR /app
 
ENV GO111MODULE on
RUN go get github.com/ob-vss-ws19/blatt-4-klausklausklaus@blatt4
RUN cp -rf /go/pkg/mod/github.com/ob-vss-ws19/blatt-4-klausklausklaus* /go/pkg/mod/github.com/ob-vss-ws19/blatt-4-klausklausklaus@v0.0.0-20200112113748-89d90ddce3df

CMD go run client.go
