// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movies.proto

package movieproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Movie representation.
type Movie struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{0}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Movie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Create a movie request.
type CreateMovieRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieRequest) Reset()         { *m = CreateMovieRequest{} }
func (m *CreateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMovieRequest) ProtoMessage()    {}
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{1}
}

func (m *CreateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieRequest.Unmarshal(m, b)
}
func (m *CreateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieRequest.Marshal(b, m, deterministic)
}
func (m *CreateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieRequest.Merge(m, src)
}
func (m *CreateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMovieRequest.Size(m)
}
func (m *CreateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieRequest proto.InternalMessageInfo

func (m *CreateMovieRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Create a movie response.
type CreatedMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatedMovieResponse) Reset()         { *m = CreatedMovieResponse{} }
func (m *CreatedMovieResponse) String() string { return proto.CompactTextString(m) }
func (*CreatedMovieResponse) ProtoMessage()    {}
func (*CreatedMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{2}
}

func (m *CreatedMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedMovieResponse.Unmarshal(m, b)
}
func (m *CreatedMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedMovieResponse.Marshal(b, m, deterministic)
}
func (m *CreatedMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedMovieResponse.Merge(m, src)
}
func (m *CreatedMovieResponse) XXX_Size() int {
	return xxx_messageInfo_CreatedMovieResponse.Size(m)
}
func (m *CreatedMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedMovieResponse proto.InternalMessageInfo

func (m *CreatedMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

// Change a movie request.
type ChangeMovieRequest struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeMovieRequest) Reset()         { *m = ChangeMovieRequest{} }
func (m *ChangeMovieRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeMovieRequest) ProtoMessage()    {}
func (*ChangeMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{3}
}

func (m *ChangeMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeMovieRequest.Unmarshal(m, b)
}
func (m *ChangeMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeMovieRequest.Marshal(b, m, deterministic)
}
func (m *ChangeMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeMovieRequest.Merge(m, src)
}
func (m *ChangeMovieRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeMovieRequest.Size(m)
}
func (m *ChangeMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeMovieRequest proto.InternalMessageInfo

func (m *ChangeMovieRequest) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

// Change a movie response.
type ChangeMovieResponse struct {
	Changed              bool     `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeMovieResponse) Reset()         { *m = ChangeMovieResponse{} }
func (m *ChangeMovieResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeMovieResponse) ProtoMessage()    {}
func (*ChangeMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{4}
}

func (m *ChangeMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeMovieResponse.Unmarshal(m, b)
}
func (m *ChangeMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeMovieResponse.Marshal(b, m, deterministic)
}
func (m *ChangeMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeMovieResponse.Merge(m, src)
}
func (m *ChangeMovieResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeMovieResponse.Size(m)
}
func (m *ChangeMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeMovieResponse proto.InternalMessageInfo

func (m *ChangeMovieResponse) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

//Find a movie request.
type FindMovieRequest struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMovieRequest) Reset()         { *m = FindMovieRequest{} }
func (m *FindMovieRequest) String() string { return proto.CompactTextString(m) }
func (*FindMovieRequest) ProtoMessage()    {}
func (*FindMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{5}
}

func (m *FindMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMovieRequest.Unmarshal(m, b)
}
func (m *FindMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMovieRequest.Marshal(b, m, deterministic)
}
func (m *FindMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMovieRequest.Merge(m, src)
}
func (m *FindMovieRequest) XXX_Size() int {
	return xxx_messageInfo_FindMovieRequest.Size(m)
}
func (m *FindMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMovieRequest proto.InternalMessageInfo

func (m *FindMovieRequest) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

// Find a movie response.
type FindMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMovieResponse) Reset()         { *m = FindMovieResponse{} }
func (m *FindMovieResponse) String() string { return proto.CompactTextString(m) }
func (*FindMovieResponse) ProtoMessage()    {}
func (*FindMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{6}
}

func (m *FindMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMovieResponse.Unmarshal(m, b)
}
func (m *FindMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMovieResponse.Marshal(b, m, deterministic)
}
func (m *FindMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMovieResponse.Merge(m, src)
}
func (m *FindMovieResponse) XXX_Size() int {
	return xxx_messageInfo_FindMovieResponse.Size(m)
}
func (m *FindMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMovieResponse proto.InternalMessageInfo

func (m *FindMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

// Delete a movie request.
type DeleteMovieRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{7}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Delete a movie response.
type DeleteMovieResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResponse) Reset()         { *m = DeleteMovieResponse{} }
func (m *DeleteMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResponse) ProtoMessage()    {}
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{8}
}

func (m *DeleteMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResponse.Unmarshal(m, b)
}
func (m *DeleteMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResponse.Merge(m, src)
}
func (m *DeleteMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResponse.Size(m)
}
func (m *DeleteMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResponse proto.InternalMessageInfo

func (m *DeleteMovieResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// Stream all movies request.
type StreamMovieRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMovieRequest) Reset()         { *m = StreamMovieRequest{} }
func (m *StreamMovieRequest) String() string { return proto.CompactTextString(m) }
func (*StreamMovieRequest) ProtoMessage()    {}
func (*StreamMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{9}
}

func (m *StreamMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMovieRequest.Unmarshal(m, b)
}
func (m *StreamMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMovieRequest.Marshal(b, m, deterministic)
}
func (m *StreamMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMovieRequest.Merge(m, src)
}
func (m *StreamMovieRequest) XXX_Size() int {
	return xxx_messageInfo_StreamMovieRequest.Size(m)
}
func (m *StreamMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMovieRequest proto.InternalMessageInfo

// Stream all movies response.
type StreamMovieResponse struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMovieResponse) Reset()         { *m = StreamMovieResponse{} }
func (m *StreamMovieResponse) String() string { return proto.CompactTextString(m) }
func (*StreamMovieResponse) ProtoMessage()    {}
func (*StreamMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_546d72ade507cae9, []int{10}
}

func (m *StreamMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMovieResponse.Unmarshal(m, b)
}
func (m *StreamMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMovieResponse.Marshal(b, m, deterministic)
}
func (m *StreamMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMovieResponse.Merge(m, src)
}
func (m *StreamMovieResponse) XXX_Size() int {
	return xxx_messageInfo_StreamMovieResponse.Size(m)
}
func (m *StreamMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMovieResponse proto.InternalMessageInfo

func (m *StreamMovieResponse) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

func init() {
	proto.RegisterType((*Movie)(nil), "movieproto.Movie")
	proto.RegisterType((*CreateMovieRequest)(nil), "movieproto.CreateMovieRequest")
	proto.RegisterType((*CreatedMovieResponse)(nil), "movieproto.CreatedMovieResponse")
	proto.RegisterType((*ChangeMovieRequest)(nil), "movieproto.ChangeMovieRequest")
	proto.RegisterType((*ChangeMovieResponse)(nil), "movieproto.ChangeMovieResponse")
	proto.RegisterType((*FindMovieRequest)(nil), "movieproto.FindMovieRequest")
	proto.RegisterType((*FindMovieResponse)(nil), "movieproto.FindMovieResponse")
	proto.RegisterType((*DeleteMovieRequest)(nil), "movieproto.DeleteMovieRequest")
	proto.RegisterType((*DeleteMovieResponse)(nil), "movieproto.DeleteMovieResponse")
	proto.RegisterType((*StreamMovieRequest)(nil), "movieproto.StreamMovieRequest")
	proto.RegisterType((*StreamMovieResponse)(nil), "movieproto.StreamMovieResponse")
}

func init() { proto.RegisterFile("movies.proto", fileDescriptor_546d72ade507cae9) }

var fileDescriptor_546d72ade507cae9 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xdb, 0x4a, 0xc3, 0x40,
	0x10, 0x4d, 0x52, 0x53, 0xed, 0x44, 0xc4, 0x4e, 0xfb, 0x10, 0x82, 0x97, 0xb0, 0x08, 0x46, 0x84,
	0x08, 0xf5, 0x51, 0x45, 0xa1, 0xe2, 0x83, 0x20, 0x68, 0xfc, 0x82, 0x68, 0x16, 0x0d, 0x98, 0xa4,
	0x26, 0xd1, 0xbf, 0xf1, 0x5f, 0xa5, 0x9b, 0x34, 0x9d, 0xcd, 0xa6, 0xa0, 0x7d, 0xdb, 0xd9, 0x39,
	0x73, 0xe6, 0x72, 0x0e, 0x6c, 0x27, 0xd9, 0x77, 0xcc, 0x0b, 0x7f, 0x96, 0x67, 0x65, 0x86, 0x20,
	0x22, 0xf1, 0x66, 0xa7, 0x60, 0x3e, 0xcc, 0x23, 0xdc, 0x01, 0x23, 0x8e, 0x6c, 0xdd, 0xd5, 0x3d,
	0x33, 0x30, 0xe2, 0x08, 0x11, 0x36, 0xd2, 0x30, 0xe1, 0xb6, 0xe1, 0xea, 0xde, 0x20, 0x10, 0x6f,
	0xe6, 0x01, 0x4e, 0x73, 0x1e, 0x96, 0x5c, 0x94, 0x04, 0xfc, 0xf3, 0x8b, 0x17, 0x65, 0x83, 0xd4,
	0x09, 0xf2, 0x1a, 0xc6, 0x15, 0x32, 0xaa, 0xa1, 0xc5, 0x2c, 0x4b, 0x0b, 0x8e, 0xc7, 0x60, 0x8a,
	0xe6, 0x02, 0x6c, 0x4d, 0x86, 0xfe, 0x72, 0x14, 0xbf, 0x42, 0x56, 0x79, 0x76, 0x05, 0x38, 0x7d,
	0x0f, 0xd3, 0x37, 0xb9, 0xd5, 0x9f, 0xcb, 0xcf, 0x60, 0x24, 0x95, 0xd7, 0xed, 0x6d, 0xd8, 0x7c,
	0x15, 0xdf, 0xd5, 0xa6, 0x5b, 0xc1, 0x22, 0x64, 0x17, 0xb0, 0x7b, 0x17, 0xa7, 0xd1, 0x7a, 0xdd,
	0x2e, 0x61, 0x48, 0x8a, 0xff, 0xbb, 0xea, 0x11, 0xe0, 0x2d, 0xff, 0xe0, 0xad, 0xab, 0xb6, 0xf4,
	0x98, 0x6f, 0x24, 0xa1, 0x96, 0x1b, 0x45, 0xe2, 0xbb, 0xd9, 0xa8, 0x0e, 0xd9, 0x18, 0xf0, 0xb9,
	0xcc, 0x79, 0x98, 0x50, 0x5a, 0x76, 0x03, 0x23, 0xe9, 0xb7, 0xa6, 0x39, 0x81, 0x7e, 0x65, 0x11,
	0x5b, 0x77, 0x7b, 0xdd, 0xd3, 0xd6, 0x80, 0xc9, 0x4f, 0x6f, 0x81, 0xc5, 0x27, 0xb0, 0x88, 0x1f,
	0xf0, 0x80, 0x16, 0xa9, 0x46, 0x71, 0x5c, 0x35, 0x2f, 0xdf, 0x8c, 0x69, 0xf8, 0x08, 0x16, 0x11,
	0xae, 0x45, 0xa9, 0x18, 0xc2, 0x39, 0x5c, 0x99, 0xa7, 0x8c, 0xe4, 0x70, 0x32, 0xa3, 0x7a, 0x77,
	0x99, 0xb1, 0xe3, 0xe2, 0x4c, 0xc3, 0x7b, 0x18, 0x34, 0x72, 0xe3, 0x1e, 0xc5, 0xb7, 0x2d, 0xe4,
	0xec, 0xaf, 0xc8, 0xd2, 0xe9, 0x88, 0x1e, 0xf2, 0x74, 0xaa, 0x7c, 0xf2, 0x74, 0x1d, 0x42, 0x32,
	0xed, 0xa5, 0x2f, 0x92, 0xe7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x99, 0x8f, 0x01, 0xf4,
	0x03, 0x00, 0x00,
}
