# Dockerfile for the movies-services

FROM obraun/vss-protoactor-jenkins as builder
COPY . /app
WORKDIR /app/cinemahall
 
RUN go build -o cinemahall main.go

FROM iron/go
EXPOSE 8200
ENTRYPOINT ["/app/cinemahall"]