// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/show.proto

package showproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Show service

type ShowService interface {
	CreateShow(ctx context.Context, in *CreateShowRequest, opts ...client.CallOption) (*CreateShowResponse, error)
	DeleteShow(ctx context.Context, in *DeleteShowRequest, opts ...client.CallOption) (*DeleteShowResponse, error)
	DeleteShowCinema(ctx context.Context, in *DeleteShowCinemaRequest, opts ...client.CallOption) (*DeleteShowCinemaResponse, error)
	DeleteShowMovie(ctx context.Context, in *DeleteShowMovieRequest, opts ...client.CallOption) (*DeleteShowMovieResponse, error)
	ListShow(ctx context.Context, in *ListShowRequest, opts ...client.CallOption) (*ListShowResponse, error)
	FindShowCinema(ctx context.Context, in *FindShowCinemaRequest, opts ...client.CallOption) (*FindShowCinemaResponse, error)
	FindShowMovie(ctx context.Context, in *FindShowMovieRequest, opts ...client.CallOption) (*FindShowMovieResponse, error)
}

type showService struct {
	c    client.Client
	name string
}

func NewShowService(name string, c client.Client) ShowService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "showproto"
	}
	return &showService{
		c:    c,
		name: name,
	}
}

func (c *showService) CreateShow(ctx context.Context, in *CreateShowRequest, opts ...client.CallOption) (*CreateShowResponse, error) {
	req := c.c.NewRequest(c.name, "Show.CreateShow", in)
	out := new(CreateShowResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showService) DeleteShow(ctx context.Context, in *DeleteShowRequest, opts ...client.CallOption) (*DeleteShowResponse, error) {
	req := c.c.NewRequest(c.name, "Show.DeleteShow", in)
	out := new(DeleteShowResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showService) DeleteShowCinema(ctx context.Context, in *DeleteShowCinemaRequest, opts ...client.CallOption) (*DeleteShowCinemaResponse, error) {
	req := c.c.NewRequest(c.name, "Show.DeleteShowCinema", in)
	out := new(DeleteShowCinemaResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showService) DeleteShowMovie(ctx context.Context, in *DeleteShowMovieRequest, opts ...client.CallOption) (*DeleteShowMovieResponse, error) {
	req := c.c.NewRequest(c.name, "Show.DeleteShowMovie", in)
	out := new(DeleteShowMovieResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showService) ListShow(ctx context.Context, in *ListShowRequest, opts ...client.CallOption) (*ListShowResponse, error) {
	req := c.c.NewRequest(c.name, "Show.ListShow", in)
	out := new(ListShowResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showService) FindShowCinema(ctx context.Context, in *FindShowCinemaRequest, opts ...client.CallOption) (*FindShowCinemaResponse, error) {
	req := c.c.NewRequest(c.name, "Show.FindShowCinema", in)
	out := new(FindShowCinemaResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showService) FindShowMovie(ctx context.Context, in *FindShowMovieRequest, opts ...client.CallOption) (*FindShowMovieResponse, error) {
	req := c.c.NewRequest(c.name, "Show.FindShowMovie", in)
	out := new(FindShowMovieResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Show service

type ShowHandler interface {
	CreateShow(context.Context, *CreateShowRequest, *CreateShowResponse) error
	DeleteShow(context.Context, *DeleteShowRequest, *DeleteShowResponse) error
	DeleteShowCinema(context.Context, *DeleteShowCinemaRequest, *DeleteShowCinemaResponse) error
	DeleteShowMovie(context.Context, *DeleteShowMovieRequest, *DeleteShowMovieResponse) error
	ListShow(context.Context, *ListShowRequest, *ListShowResponse) error
	FindShowCinema(context.Context, *FindShowCinemaRequest, *FindShowCinemaResponse) error
	FindShowMovie(context.Context, *FindShowMovieRequest, *FindShowMovieResponse) error
}

func RegisterShowHandler(s server.Server, hdlr ShowHandler, opts ...server.HandlerOption) error {
	type show interface {
		CreateShow(ctx context.Context, in *CreateShowRequest, out *CreateShowResponse) error
		DeleteShow(ctx context.Context, in *DeleteShowRequest, out *DeleteShowResponse) error
		DeleteShowCinema(ctx context.Context, in *DeleteShowCinemaRequest, out *DeleteShowCinemaResponse) error
		DeleteShowMovie(ctx context.Context, in *DeleteShowMovieRequest, out *DeleteShowMovieResponse) error
		ListShow(ctx context.Context, in *ListShowRequest, out *ListShowResponse) error
		FindShowCinema(ctx context.Context, in *FindShowCinemaRequest, out *FindShowCinemaResponse) error
		FindShowMovie(ctx context.Context, in *FindShowMovieRequest, out *FindShowCinemaResponse) error
	}
	type Show struct {
		show
	}
	h := &showHandler{hdlr}
	return s.Handle(s.NewHandler(&Show{h}, opts...))
}

type showHandler struct {
	ShowHandler
}

func (h *showHandler) CreateShow(ctx context.Context, in *CreateShowRequest, out *CreateShowResponse) error {
	return h.ShowHandler.CreateShow(ctx, in, out)
}

func (h *showHandler) DeleteShow(ctx context.Context, in *DeleteShowRequest, out *DeleteShowResponse) error {
	return h.ShowHandler.DeleteShow(ctx, in, out)
}

func (h *showHandler) DeleteShowCinema(ctx context.Context, in *DeleteShowCinemaRequest, out *DeleteShowCinemaResponse) error {
	return h.ShowHandler.DeleteShowCinema(ctx, in, out)
}

func (h *showHandler) DeleteShowMovie(ctx context.Context, in *DeleteShowMovieRequest, out *DeleteShowMovieResponse) error {
	return h.ShowHandler.DeleteShowMovie(ctx, in, out)
}

func (h *showHandler) ListShow(ctx context.Context, in *ListShowRequest, out *ListShowResponse) error {
	return h.ShowHandler.ListShow(ctx, in, out)
}

func (h *showHandler) FindShowCinema(ctx context.Context, in *FindShowCinemaRequest, out *FindShowCinemaResponse) error {
	return h.ShowHandler.FindShowCinema(ctx, in, out)
}

func (h *showHandler) FindShowMovie(ctx context.Context, in *FindShowMovieRequest, out *FindShowMovieResponse) error {
	return h.ShowHandler.FindShowMovie(ctx, in, out)
}
