# Dockerfile for the reservation-services

FROM obraun/vss-protoactor-jenkins as builder
COPY . /app
WORKDIR /app/reservation
 
RUN go build -o reservation main.go

FROM iron/go
EXPOSE 8200
ENTRYPOINT ["/app/reservation"]